import type { LucideIcon } from "lucide-react";
import {
    Home,
    Users,
    Briefcase,
    FileSignature,
    Package,
    Target,
    FileText,
    NotepadText,
    Tag,
    Building2,
    UserCircle,
    Layers,
    Star,
    Heart,
    Image,
    Camera,
    Video,
    MapPin,
    Globe,
    Rocket,
    Sparkles,
    Flame,
    Crown,
    Award,
    Trophy,
    Flag,
    Zap,
    Eye,
    Clock,
    Folder,
    Palette,
    Gift,
    Bookmark,
    Shield,
    Hammer,
    Truck,
    Plane,
    Coffee,
    Leaf,
    Music,
    ShoppingCart,
    Stethoscope,
} from "lucide-react";

export const PROJECT_ICONS: Record<string, LucideIcon> = {
    Home,
    Users,
    Briefcase,
    FileSignature,
    Package,
    Target,
    FileText,
    NotepadText,
    Tag,
    Building2,
    UserCircle,
    Layers,
    Star,
    Heart,
    Image,
    Camera,
    Video,
    MapPin,
    Globe,
    Rocket,
    Sparkles,
    Flame,
    Crown,
    Award,
    Trophy,
    Flag,
    Zap,
    Eye,
    Clock,
    Folder,
    Palette,
    Gift,
    Bookmark,
    Shield,
    Hammer,
    Truck,
    Plane,
    Coffee,
    Leaf,
    Music,
    ShoppingCart,
    Stethoscope,
};

export const PROJECT_ICON_NAMES: string[] = Object.keys(PROJECT_ICONS);

export const getProjectIcon = (name?: string | null): LucideIcon | null => {
    if (!name) return null;
    return PROJECT_ICONS[name] || null;
};
